import localFont from "next/font/local";

/**
 * Display-only MiSans Semibold subset for the /story/ headings — a separate,
 * larger glyph set than the landing's misans-display-zh.woff2, kept in its
 * own module so importing it never preloads on the landing pages (and vice
 * versa). Regenerated by scripts/subset-zh-font.mjs.
 */
export const storyZhDisplay = localFont({
  src: "../app/fonts/misans-display-story.woff2",
  weight: "600",
  display: "swap",
  variable: "--font-zh-display",
});
