// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	settingsGet: () => typedError<SettingsDto, string>(__TAURI_INVOKE("settings_get")),
	settingsSet: (patch: SettingsPatch) => typedError<SettingsDto, string>(__TAURI_INVOKE("settings_set", { patch })),
	wallpaperGetScreens: () => typedError<WallpaperScreensDto, string>(__TAURI_INVOKE("wallpaper_get_screens")),
	wallpaperApplyBaked: (monitorId: string, pngBase64: string) => typedError<WallpaperResultDto, string>(__TAURI_INVOKE("wallpaper_apply_baked", { monitorId, pngBase64 })),
	wallpaperRestore: (monitorId: string) => typedError<WallpaperResultDto, string>(__TAURI_INVOKE("wallpaper_restore", { monitorId })),
	iconsScan: () => typedError<IconScanDto, string>(__TAURI_INVOKE("icons_scan")),
	iconsGetPersisted: () => typedError<IconPersistedDto, string>(__TAURI_INVOKE("icons_get_persisted")),
	iconsApplyBakedBegin: (revision: number, count: number) => typedError<null, string>(__TAURI_INVOKE("icons_apply_baked_begin", { revision, count })),
	iconsApplyBakedChunk: (items: IconChunkItemDto[]) => typedError<null, string>(__TAURI_INVOKE("icons_apply_baked_chunk", { items })),
	iconsApplyBakedCommit: (styleJson: string, restoreIds: string[], label: string | null) => typedError<IconOpResultDto, string>(__TAURI_INVOKE("icons_apply_baked_commit", { styleJson, restoreIds, label })),
	iconsRestore: () => typedError<IconOpResultDto, string>(__TAURI_INVOKE("icons_restore")),
	iconsRestoreOverlay: () => typedError<IconOpResultDto, string>(__TAURI_INVOKE("icons_restore_overlay")),
	iconsExportCompare: () => typedError<IconOpResultDto, string>(__TAURI_INVOKE("icons_export_compare")),
};

/* Types */
/**
 *  The native shortcut-arrow overlay state (ADR-0021 machine-wide overlay). `native` = Windows
 *  draws its own arrow (pre-first-apply, or after a restore); `hidden` = the global transparent
 *  overlay is installed and DeskMakeover draws the mark. Serialized lowercase to match the TS
 *  `'native' | 'hidden'` union.
 */
export type ArrowOverlayDto = "native" | "hidden";

/**
 *  The OBSERVED desktop metrics a scan reports, so the frontend assembles the grid from PLATFORM
 *  truth instead of fabricating dims (codex Major 5 — a hardcoded 1920×1080 lies on 4K/ultrawide/
 *  side-taskbar desktops). The frontend derives `iconPx`/cell sizes from these + the chosen size.
 *  [WINDOWS-VERIFY] the real `SPI_GETWORKAREA` + shell icon metrics on the box; the dev host
 *  synthesizes plausible values.
 */
export type GridMetricsDto = {
	screenWidth: number,
	screenHeight: number,
	taskbarHeight: number,
};

/**
 *  One baked master in an `icons.applyBakedChunk` batch (a command INPUT). `sourceIndex` 0 =
 *  primary, 1 = paired empty (Recycle Bin); `masterPng` is the base64 256px straight-alpha RGBA
 *  PNG the frontend WASM-baked. Mirrors the TS `icons.applyBakedChunk` item shape.
 */
export type IconChunkItemDto = {
	id: string,
	sourceIndex: number,
	masterPng: string,
};

/**
 *  One desktop item as the scanner observed it — raw platform truth ONLY (no override, no style).
 *  The frontend overlays its own draft per-icon overrides + renders the styling locally from
 *  `sourceUrls` (256px, `[0]` primary; the Recycle Bin ships TWO — empty + full). Positions are
 *  OBSERVED desktop truth, never predicted. Mirrors the styleable subset of the TS `IconItemDto`
 *  (the TS shape additionally carries the frontend-owned `overrideMode`/`overrideTint`).
 */
export type IconItemDto = {
	id: string,
	label: string,
	kind: IconKindDto,
	isShortcut: boolean,
	styleable: boolean,
	/**
	 *  Host-localized human reason when `styleable` is false (e.g. a genuinely unreadable item);
	 *  `None` when styleable.
	 */
	statusReason: string | null,
	x: number,
	y: number,
	/**
	 *  The item's 256px source URL(s) the compositor renders from; `[0]` is primary. The Recycle
	 *  Bin carries two (empty + full).
	 */
	sourceUrls: string[],
};

/**
 *  The kind of one desktop item (spec 06 §6 taxonomy). Serialized as the variant name to match
 *  the TS `IconKind` union. `SystemIcon`/`ExecutableFile` are host-classification refinements the
 *  scanner assigns; the operations layer maps them onto its `ItemKind` write mechanisms.
 */
export type IconKindDto = "Shortcut" | "UrlShortcut" | "AppxShortcut" | "RecycleBin" | "SystemIcon" | "Folder" | "RegularFile" | "ExecutableFile" | "Unsupported";

/**
 *  The THIN result of a mutating icon op (`applyBaked*` commit / `restore` / `restoreOverlay` /
 *  `exportCompare`): success, an optional localized toast, and the FRESH persisted state so the
 *  frontend re-overlays without a second round-trip. Mirrors the TS `IconOpResultDto`.
 */
export type IconOpResultDto = {
	ok: boolean,
	toast: ToastDto | null,
	persisted: IconPersistedDto,
};

/**
 *  The persisted + native icon state the frontend overlays onto its assembled `IconsStateDto`
 *  (D1: the frontend owns presets/palette/swatches/grid/`activePresetId`/the config draft). This
 *  is what `icons.getPersisted` returns and what every mutating op reports back, so there is ONE
 *  overlay path. Mirrors the TS `IconPersistedDto`.
 */
export type IconPersistedDto = {
	/**
	 *  Store ② — the current global saved-style recipe as an opaque JSON string, or `None` when no
	 *  global Apply has ever run (the resident then treats it as "nothing to project", spec 07 §8.3).
	 */
	savedStyleJson: string | null,
	/**  Store ③ — up to 10 saved looks, newest-first (already capped + pin-normalized by the store). */
	history: LookVersionDto[],
	/**
	 *  Whether a look is currently applied (the active ledger holds at least one styled row) — the
	 *  frontend's `applied`/restore affordance authority, surviving a cold start.
	 */
	applied: boolean,
	arrowOverlay: ArrowOverlayDto,
	/**
	 *  Count of active user profiles on this machine (>1 makes the machine-wide arrow disclosure
	 *  non-skippable; owner disposition 3). Host truth on Windows.
	 */
	activeUserProfiles: number,
};

/**
 *  The result of `icons.scan`: a monotonically increasing revision, the raw observed items, and the
 *  observed desktop grid metrics. NO embedded `IconsStateDto` (D1: the frontend assembles it from
 *  these + `getPersisted` + its own presets/palette). Mirrors the TS `icons.scan` result.
 */
export type IconScanDto = {
	revision: number,
	items: IconItemDto[],
	grid: GridMetricsDto,
};

/**
 *  UI language. `System` follows the OS UI culture; the two concrete tags use
 *  the BCP-47 spellings the TS dictionaries key on.
 */
export type Language = "System" | "zh-Hans" | "en";

/**
 *  One saved appearance recipe from store ③ (look-history), mirroring `dm_operations::LookVersion`
 *  with the recipe carried as an opaque JSON string (`styleJson`). The frontend renders each
 *  entry's style-sample mini from the parsed recipe (spec 07 §8.1 — never a desktop screenshot).
 */
export type LookVersionDto = {
	id: string,
	/**
	 *  UNIX seconds as a TS `number` — specta-typescript forbids raw i64 export (JS has no i64),
	 *  and a seconds timestamp is far below 2^53 so `f64` is lossless. The host maps the store's
	 *  `i64` `created_at` in; this is output-only (the frontend never sends it back).
	 */
	createdAt: number | null,
	/**
	 *  A user-chosen name; `None` = unnamed. Independent of `pinned` (owner ruling 2026-07-12:
	 *  naming is an unlimited label, pinning is the eviction exemption).
	 */
	label: string | null,
	/**  Exempt from the store's FIFO eviction while set (spec 07 §17). */
	pinned: boolean,
	/**  The `{config, kindPolicy, typeOverrides}` recipe as an opaque JSON string (see module docs). */
	styleJson: string,
};

/**
 *  Virtual-desktop bounds of one monitor, in physical pixels (IDesktopWallpaper
 *  `GetMonitorRECT`). `x`/`y` may be negative (a monitor left of / above the
 *  primary on the virtual desktop). Mirrors the TS `MonitorBounds`.
 */
export type MonitorBounds = {
	x: number,
	y: number,
	w: number,
	h: number,
};

/**
 *  One physical monitor's raw screen info (thin, per D1: NO look, NO grid — the
 *  frontend reconciles + overlays persisted looks + assembles `WallpaperStateDto`).
 *  Mirrors the TS `ScreenInfoDto`.
 */
export type ScreenInfoDto = {
	/**
	 *  Windows device path (`GetMonitorDevicePathAt`) — durable-ish, not permanent
	 *  across port/driver/dock/EDID changes. The frontend reconciles by this path
	 *  then by exact bounds.
	 */
	monitorId: string,
	name: string,
	bounds: MonitorBounds,
	orientation: ScreenOrientation,
	/**
	 *  Decoded per-screen source; `None` when unreadable — a third-party
	 *  dynamic/video wallpaper is invisible to `IDesktopWallpaper` (import CTA).
	 */
	source: WallpaperSourceDto | null,
	/**  Windows slideshow active on this monitor (rotation won't re-arm after apply). */
	slideshowActive: boolean,
	/**
	 *  `GetWallpaper` returned a readable image path (`false` ⇒ dynamic/video
	 *  wallpaper — distinct from a solid-colour desktop, which reads readable-empty).
	 */
	hasReadableSource: boolean,
};

/**
 *  Screen orientation, derived from the bounds aspect (`h > w` ⇒ portrait).
 *  Serialized lowercase to match the TS `ScreenOrientation` union.
 */
export type ScreenOrientation = "portrait" | "landscape";

/**  The full persisted settings row (spec 03 appearance + participation coach). */
export type SettingsDto = {
	theme: Theme,
	language: Language,
	keepNewIconsStyled: boolean,
	wallpaperCoachShown: boolean,
};

/**
 *  Sparse update over [`SettingsDto`] — every field absent (or `null`) leaves
 *  the stored value untouched. Mirrors the TS `SettingsPatch = Partial<SettingsDto>`.
 */
export type SettingsPatch = {
	theme?: Theme | null,
	language?: Language | null,
	keepNewIconsStyled?: boolean | null,
	wallpaperCoachShown?: boolean | null,
};

/**
 *  Appearance theme. Serialized as its variant name (`"System"` | `"Dark"` |
 *  `"Light"`) to match the TS union.
 */
export type Theme = "System" | "Dark" | "Light";

/**
 *  A localized toast the host asks the shell to show: `key` is an i18n key and
 *  `arg` an optional interpolation argument. Mirrors the TS `ToastDto`. Shared:
 *  the wallpaper module (Wave A) and the icons module (Wave B) both return it
 *  from mutating ops.
 */
export type ToastDto = {
	key: string,
	arg: string | null,
};

/**
 *  GLOBAL wallpaper positioning (Windows `DesktopWallpaperPosition`). Only image
 *  PATHS are per-monitor; position/slideshow/bg-color are whole-desktop. `Span`
 *  stretches ONE image across every monitor. Serialized as the variant name to
 *  match the TS `WallpaperPosition` union.
 */
export type WallpaperPosition = "Center" | "Tile" | "Stretch" | "Fit" | "Fill" | "Span";

/**
 *  The THIN result of a mutating wallpaper op (`applyBaked` / `restore`). Per D1 the
 *  host does NOT assemble `WallpaperStateDto`; it reports only success, an optional
 *  toast, and whether a pre-first-apply snapshot now exists (so the frontend can
 *  enable the whole-desktop restore affordance). The frontend re-fetches
 *  `getScreens` and re-assembles state itself. Mirrors the TS `WallpaperResultDto`.
 */
export type WallpaperResultDto = {
	ok: boolean,
	toast: ToastDto | null,
	/**
	 *  `true` once the pre-first-apply snapshot has been captured and persisted —
	 *  the single durable guard against the first apply destroying the original
	 *  desktop with no way back.
	 */
	hasBackup: boolean,
};

/**
 *  The THIN screen enumeration `wallpaper.getScreens` returns: raw screens + global
 *  desktop flags only. NO looks, NO grids, NO reconcile (D1: all frontend). Mirrors
 *  the TS `wallpaper.getScreens` result.
 */
export type WallpaperScreensDto = {
	screens: ScreenInfoDto[],
	position: WallpaperPosition,
	/**
	 *  `position == Span` — the UI degrades to a unified canvas. Reported
	 *  explicitly (the host detects it) rather than derived. Mirrors the TS
	 *  `spanActive`.
	 */
	spanActive: boolean,
	/**
	 *  Whether a durable pre-first-apply snapshot exists on disk. Carried on
	 *  getScreens (not only on mutating-op results) so a COLD START surfaces the
	 *  whole-desktop "restore to original" affordance when a snapshot persists —
	 *  without it, a restart after an apply hides the only path back.
	 */
	hasBackup: boolean,
};

/**
 *  Decoded, cover-cropped source the compositor renders from. On the host `url` is
 *  the `dmwallpaper://<monitorId>?rev=N` custom-protocol URL (WIC-decoded PNG); in
 *  the mock it is the scene bitmap URL. `width`/`height` are the DECODED image's
 *  true pixel dims (NOT the monitor bounds), so the compositor cover-crops to each
 *  screen's aspect. Mirrors the TS `WallpaperSourceDto`.
 */
export type WallpaperSourceDto = {
	url: string,
	width: number,
	height: number,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

