// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	settingsGet: () => typedError<SettingsDto, string>(__TAURI_INVOKE("settings_get")),
	settingsSet: (patch: SettingsPatch) => typedError<SettingsDto, string>(__TAURI_INVOKE("settings_set", { patch })),
	diagnosticsPing: (message: string) => __TAURI_INVOKE<DiagnosticsPing>("diagnostics_ping", { message }),
};

/* Types */
/**
 *  Reply to `diagnostics_ping` — echoes the caller's message and reports the
 *  backend version, so the frontend can confirm it is talking to a live host.
 */
export type DiagnosticsPing = {
	ok: boolean,
	version: string,
	message: string,
};

/**
 *  UI language. `System` follows the OS UI culture; the two concrete tags use
 *  the BCP-47 spellings the TS dictionaries key on.
 */
export type Language = "System" | "zh-Hans" | "en";

/**  The full persisted settings row (spec 03 appearance + participation coach). */
export type SettingsDto = {
	theme: Theme,
	language: Language,
	keepNewIconsStyled: boolean,
	wallpaperCoachShown: boolean,
};

/**
 *  Sparse update over [`SettingsDto`] — every field absent (or `null`) leaves
 *  the stored value untouched. Mirrors the TS `SettingsPatch = Partial<SettingsDto>`.
 */
export type SettingsPatch = {
	theme?: Theme | null,
	language?: Language | null,
	keepNewIconsStyled?: boolean | null,
	wallpaperCoachShown?: boolean | null,
};

/**
 *  Appearance theme. Serialized as its variant name (`"System"` | `"Dark"` |
 *  `"Light"`) to match the TS union.
 */
export type Theme = "System" | "Dark" | "Light";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

