// Generates src/lib/i18n/{en,zh-hans}.ts from the WPF resx tables (one-way:
// resx → TS). Run with: bun scripts/resx-to-i18n.ts
// After P6 deletes the WPF resources the generated files become the source.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { join } from 'node:path'

const appRes = join(import.meta.dir, '..', 'legacy', 'src', 'DeskMakeover.App', 'Resources')
const outDir = join(import.meta.dir, '..', 'src', 'lib', 'i18n')

function parseResx(path: string): Map<string, string> {
  const xml = readFileSync(path, 'utf8')
  const map = new Map<string, string>()
  const re = /<data name="([^"]+)"[^>]*>\s*<value>([\s\S]*?)<\/value>/g
  let m: RegExpExecArray | null
  while ((m = re.exec(xml))) {
    const value = m[2]
      .replaceAll('&amp;', '&')
      .replaceAll('&lt;', '<')
      .replaceAll('&gt;', '>')
      .replaceAll('&quot;', '"')
      .replaceAll('&apos;', "'")
    map.set(m[1], value)
  }
  return map
}

const en = parseResx(join(appRes, 'Strings.resx'))
const zh = parseResx(join(appRes, 'Strings.zh-Hans.resx'))

const missingInZh = [...en.keys()].filter((k) => !zh.has(k))
const missingInEn = [...zh.keys()].filter((k) => !en.has(k))
if (missingInZh.length || missingInEn.length) {
  console.error('key parity failure', { missingInZh, missingInEn })
  process.exit(1)
}

function emit(file: string, name: string, map: Map<string, string>, typed: boolean) {
  const keys = [...map.keys()].sort()
  const body = keys.map((k) => `  ${JSON.stringify(k)}: ${JSON.stringify(map.get(k))},`).join('\n')
  const header = '// GENERATED by scripts/resx-to-i18n.ts — do not edit by hand.\n'
  const decl = typed
    ? `import type { en } from './en'\n\nexport const ${name}: Record<keyof typeof en, string> = {\n`
    : `export const ${name} = {\n`
  writeFileSync(join(outDir, file), `${header}${decl}${body}\n}${typed ? '' : ' as const'}\n`)
}

mkdirSync(outDir, { recursive: true })
emit('en.ts', 'en', en, false)
emit('zh-hans.ts', 'zhHans', zh, true)
console.log(`emitted ${en.size} keys → src/lib/i18n/{en,zh-hans}.ts`)
